# Generated by Django 4.2.1 on 2023-06-03 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_pictures', '0003_remove_icom_format_base64_alter_icom_format_icon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icom_format',
            new_name='IconFormat',
        ),
    ]
